// source: Protos/Customer.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var Protos_Common_pb = require('../Protos/Common_pb.js');
goog.object.extend(proto, Protos_Common_pb);
goog.exportSymbol('proto.Protos.CancelCustomerRequest', null, global);
goog.exportSymbol('proto.Protos.CancelCustomerResponse', null, global);
goog.exportSymbol('proto.Protos.CreateCustomerRequest', null, global);
goog.exportSymbol('proto.Protos.CreateCustomerResponse', null, global);
goog.exportSymbol('proto.Protos.CustomerDocumentType', null, global);
goog.exportSymbol('proto.Protos.CustomerResponse', null, global);
goog.exportSymbol('proto.Protos.CustomerState', null, global);
goog.exportSymbol('proto.Protos.GetAllCustomerRequest', null, global);
goog.exportSymbol('proto.Protos.GetAllCustomerResponse', null, global);
goog.exportSymbol('proto.Protos.GetCustomerByDniRequest', null, global);
goog.exportSymbol('proto.Protos.GetCustomerRequest', null, global);
goog.exportSymbol('proto.Protos.GetCustomerResponse', null, global);
goog.exportSymbol('proto.Protos.UpdateCustomerRequest', null, global);
goog.exportSymbol('proto.Protos.UpdateCustomerResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetCustomerByDniRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetCustomerByDniRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetCustomerByDniRequest.displayName = 'proto.Protos.GetCustomerByDniRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CreateCustomerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CreateCustomerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CreateCustomerRequest.displayName = 'proto.Protos.CreateCustomerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CreateCustomerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CreateCustomerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CreateCustomerResponse.displayName = 'proto.Protos.CreateCustomerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.UpdateCustomerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.UpdateCustomerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.UpdateCustomerRequest.displayName = 'proto.Protos.UpdateCustomerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.UpdateCustomerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.UpdateCustomerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.UpdateCustomerResponse.displayName = 'proto.Protos.UpdateCustomerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CancelCustomerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CancelCustomerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CancelCustomerRequest.displayName = 'proto.Protos.CancelCustomerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CancelCustomerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CancelCustomerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CancelCustomerResponse.displayName = 'proto.Protos.CancelCustomerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetCustomerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetCustomerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetCustomerRequest.displayName = 'proto.Protos.GetCustomerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetCustomerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetCustomerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetCustomerResponse.displayName = 'proto.Protos.GetCustomerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetAllCustomerRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetAllCustomerRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetAllCustomerRequest.displayName = 'proto.Protos.GetAllCustomerRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetAllCustomerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Protos.GetAllCustomerResponse.repeatedFields_, null);
};
goog.inherits(proto.Protos.GetAllCustomerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetAllCustomerResponse.displayName = 'proto.Protos.GetAllCustomerResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CustomerResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CustomerResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CustomerResponse.displayName = 'proto.Protos.CustomerResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetCustomerByDniRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetCustomerByDniRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetCustomerByDniRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetCustomerByDniRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    nrodocumento: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetCustomerByDniRequest}
 */
proto.Protos.GetCustomerByDniRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetCustomerByDniRequest;
  return proto.Protos.GetCustomerByDniRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetCustomerByDniRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetCustomerByDniRequest}
 */
proto.Protos.GetCustomerByDniRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNrodocumento(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetCustomerByDniRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetCustomerByDniRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetCustomerByDniRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetCustomerByDniRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNrodocumento();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 NroDocumento = 1;
 * @return {number}
 */
proto.Protos.GetCustomerByDniRequest.prototype.getNrodocumento = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.GetCustomerByDniRequest} returns this
 */
proto.Protos.GetCustomerByDniRequest.prototype.setNrodocumento = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CreateCustomerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CreateCustomerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CreateCustomerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateCustomerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    nombre: jspb.Message.getFieldWithDefault(msg, 1, ""),
    apellidopaterno: jspb.Message.getFieldWithDefault(msg, 2, ""),
    apellidomaterno: jspb.Message.getFieldWithDefault(msg, 3, ""),
    celular: jspb.Message.getFieldWithDefault(msg, 4, ""),
    email: jspb.Message.getFieldWithDefault(msg, 5, ""),
    tipodocumento: jspb.Message.getFieldWithDefault(msg, 6, 0),
    nrodocumento: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CreateCustomerRequest}
 */
proto.Protos.CreateCustomerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CreateCustomerRequest;
  return proto.Protos.CreateCustomerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CreateCustomerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CreateCustomerRequest}
 */
proto.Protos.CreateCustomerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNombre(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApellidopaterno(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApellidomaterno(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCelular(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 6:
      var value = /** @type {!proto.Protos.CustomerDocumentType} */ (reader.readEnum());
      msg.setTipodocumento(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNrodocumento(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CreateCustomerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CreateCustomerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CreateCustomerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateCustomerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNombre();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApellidopaterno();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getApellidomaterno();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCelular();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTipodocumento();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
  f = message.getNrodocumento();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional string Nombre = 1;
 * @return {string}
 */
proto.Protos.CreateCustomerRequest.prototype.getNombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setNombre = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string ApellidoPaterno = 2;
 * @return {string}
 */
proto.Protos.CreateCustomerRequest.prototype.getApellidopaterno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setApellidopaterno = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ApellidoMaterno = 3;
 * @return {string}
 */
proto.Protos.CreateCustomerRequest.prototype.getApellidomaterno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setApellidomaterno = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string Celular = 4;
 * @return {string}
 */
proto.Protos.CreateCustomerRequest.prototype.getCelular = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setCelular = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string email = 5;
 * @return {string}
 */
proto.Protos.CreateCustomerRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional CustomerDocumentType TipoDocumento = 6;
 * @return {!proto.Protos.CustomerDocumentType}
 */
proto.Protos.CreateCustomerRequest.prototype.getTipodocumento = function() {
  return /** @type {!proto.Protos.CustomerDocumentType} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.Protos.CustomerDocumentType} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setTipodocumento = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};


/**
 * optional int32 NroDocumento = 7;
 * @return {number}
 */
proto.Protos.CreateCustomerRequest.prototype.getNrodocumento = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CreateCustomerRequest} returns this
 */
proto.Protos.CreateCustomerRequest.prototype.setNrodocumento = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CreateCustomerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CreateCustomerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CreateCustomerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateCustomerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CreateCustomerResponse}
 */
proto.Protos.CreateCustomerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CreateCustomerResponse;
  return proto.Protos.CreateCustomerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CreateCustomerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CreateCustomerResponse}
 */
proto.Protos.CreateCustomerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CreateCustomerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CreateCustomerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CreateCustomerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateCustomerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.CreateCustomerResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.CreateCustomerResponse} returns this
*/
proto.Protos.CreateCustomerResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.CreateCustomerResponse} returns this
 */
proto.Protos.CreateCustomerResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.CreateCustomerResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.UpdateCustomerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.UpdateCustomerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.UpdateCustomerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateCustomerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nombre: jspb.Message.getFieldWithDefault(msg, 2, ""),
    apellidopaterno: jspb.Message.getFieldWithDefault(msg, 3, ""),
    apellidomaterno: jspb.Message.getFieldWithDefault(msg, 4, ""),
    celular: jspb.Message.getFieldWithDefault(msg, 5, ""),
    email: jspb.Message.getFieldWithDefault(msg, 6, ""),
    tipodocumento: jspb.Message.getFieldWithDefault(msg, 7, 0),
    nrodocumento: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.UpdateCustomerRequest}
 */
proto.Protos.UpdateCustomerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.UpdateCustomerRequest;
  return proto.Protos.UpdateCustomerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.UpdateCustomerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.UpdateCustomerRequest}
 */
proto.Protos.UpdateCustomerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNombre(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApellidopaterno(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setApellidomaterno(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCelular(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 7:
      var value = /** @type {!proto.Protos.CustomerDocumentType} */ (reader.readEnum());
      msg.setTipodocumento(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNrodocumento(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.UpdateCustomerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.UpdateCustomerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.UpdateCustomerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateCustomerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNombre();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getApellidopaterno();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getApellidomaterno();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCelular();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTipodocumento();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getNrodocumento();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.UpdateCustomerRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Nombre = 2;
 * @return {string}
 */
proto.Protos.UpdateCustomerRequest.prototype.getNombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setNombre = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ApellidoPaterno = 3;
 * @return {string}
 */
proto.Protos.UpdateCustomerRequest.prototype.getApellidopaterno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setApellidopaterno = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string ApellidoMaterno = 4;
 * @return {string}
 */
proto.Protos.UpdateCustomerRequest.prototype.getApellidomaterno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setApellidomaterno = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Celular = 5;
 * @return {string}
 */
proto.Protos.UpdateCustomerRequest.prototype.getCelular = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setCelular = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string email = 6;
 * @return {string}
 */
proto.Protos.UpdateCustomerRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional CustomerDocumentType TipoDocumento = 7;
 * @return {!proto.Protos.CustomerDocumentType}
 */
proto.Protos.UpdateCustomerRequest.prototype.getTipodocumento = function() {
  return /** @type {!proto.Protos.CustomerDocumentType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.Protos.CustomerDocumentType} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setTipodocumento = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional int32 NroDocumento = 8;
 * @return {number}
 */
proto.Protos.UpdateCustomerRequest.prototype.getNrodocumento = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.UpdateCustomerRequest} returns this
 */
proto.Protos.UpdateCustomerRequest.prototype.setNrodocumento = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.UpdateCustomerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.UpdateCustomerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.UpdateCustomerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateCustomerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.Protos.CustomerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.UpdateCustomerResponse}
 */
proto.Protos.UpdateCustomerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.UpdateCustomerResponse;
  return proto.Protos.UpdateCustomerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.UpdateCustomerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.UpdateCustomerResponse}
 */
proto.Protos.UpdateCustomerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.Protos.CustomerResponse;
      reader.readMessage(value,proto.Protos.CustomerResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.UpdateCustomerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.UpdateCustomerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.UpdateCustomerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateCustomerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Protos.CustomerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.UpdateCustomerResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.UpdateCustomerResponse} returns this
*/
proto.Protos.UpdateCustomerResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.UpdateCustomerResponse} returns this
 */
proto.Protos.UpdateCustomerResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.UpdateCustomerResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CustomerResponse Data = 2;
 * @return {?proto.Protos.CustomerResponse}
 */
proto.Protos.UpdateCustomerResponse.prototype.getData = function() {
  return /** @type{?proto.Protos.CustomerResponse} */ (
    jspb.Message.getWrapperField(this, proto.Protos.CustomerResponse, 2));
};


/**
 * @param {?proto.Protos.CustomerResponse|undefined} value
 * @return {!proto.Protos.UpdateCustomerResponse} returns this
*/
proto.Protos.UpdateCustomerResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.UpdateCustomerResponse} returns this
 */
proto.Protos.UpdateCustomerResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.UpdateCustomerResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CancelCustomerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CancelCustomerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CancelCustomerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelCustomerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CancelCustomerRequest}
 */
proto.Protos.CancelCustomerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CancelCustomerRequest;
  return proto.Protos.CancelCustomerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CancelCustomerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CancelCustomerRequest}
 */
proto.Protos.CancelCustomerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CancelCustomerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CancelCustomerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CancelCustomerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelCustomerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.CancelCustomerRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CancelCustomerRequest} returns this
 */
proto.Protos.CancelCustomerRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CancelCustomerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CancelCustomerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CancelCustomerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelCustomerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CancelCustomerResponse}
 */
proto.Protos.CancelCustomerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CancelCustomerResponse;
  return proto.Protos.CancelCustomerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CancelCustomerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CancelCustomerResponse}
 */
proto.Protos.CancelCustomerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CancelCustomerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CancelCustomerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CancelCustomerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelCustomerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.CancelCustomerResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.CancelCustomerResponse} returns this
*/
proto.Protos.CancelCustomerResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.CancelCustomerResponse} returns this
 */
proto.Protos.CancelCustomerResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.CancelCustomerResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetCustomerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetCustomerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetCustomerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetCustomerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetCustomerRequest}
 */
proto.Protos.GetCustomerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetCustomerRequest;
  return proto.Protos.GetCustomerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetCustomerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetCustomerRequest}
 */
proto.Protos.GetCustomerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetCustomerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetCustomerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetCustomerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetCustomerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.GetCustomerRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.GetCustomerRequest} returns this
 */
proto.Protos.GetCustomerRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetCustomerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetCustomerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetCustomerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetCustomerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.Protos.CustomerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetCustomerResponse}
 */
proto.Protos.GetCustomerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetCustomerResponse;
  return proto.Protos.GetCustomerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetCustomerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetCustomerResponse}
 */
proto.Protos.GetCustomerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.Protos.CustomerResponse;
      reader.readMessage(value,proto.Protos.CustomerResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetCustomerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetCustomerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetCustomerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetCustomerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Protos.CustomerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.GetCustomerResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.GetCustomerResponse} returns this
*/
proto.Protos.GetCustomerResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.GetCustomerResponse} returns this
 */
proto.Protos.GetCustomerResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.GetCustomerResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CustomerResponse Data = 2;
 * @return {?proto.Protos.CustomerResponse}
 */
proto.Protos.GetCustomerResponse.prototype.getData = function() {
  return /** @type{?proto.Protos.CustomerResponse} */ (
    jspb.Message.getWrapperField(this, proto.Protos.CustomerResponse, 2));
};


/**
 * @param {?proto.Protos.CustomerResponse|undefined} value
 * @return {!proto.Protos.GetCustomerResponse} returns this
*/
proto.Protos.GetCustomerResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.GetCustomerResponse} returns this
 */
proto.Protos.GetCustomerResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.GetCustomerResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetAllCustomerRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetAllCustomerRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetAllCustomerRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllCustomerRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetAllCustomerRequest}
 */
proto.Protos.GetAllCustomerRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetAllCustomerRequest;
  return proto.Protos.GetAllCustomerRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetAllCustomerRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetAllCustomerRequest}
 */
proto.Protos.GetAllCustomerRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetAllCustomerRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetAllCustomerRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetAllCustomerRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllCustomerRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Protos.GetAllCustomerResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetAllCustomerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetAllCustomerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetAllCustomerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllCustomerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.Protos.CustomerResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetAllCustomerResponse}
 */
proto.Protos.GetAllCustomerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetAllCustomerResponse;
  return proto.Protos.GetAllCustomerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetAllCustomerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetAllCustomerResponse}
 */
proto.Protos.GetAllCustomerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.Protos.CustomerResponse;
      reader.readMessage(value,proto.Protos.CustomerResponse.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetAllCustomerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetAllCustomerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetAllCustomerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllCustomerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Protos.CustomerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.GetAllCustomerResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.GetAllCustomerResponse} returns this
*/
proto.Protos.GetAllCustomerResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.GetAllCustomerResponse} returns this
 */
proto.Protos.GetAllCustomerResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.GetAllCustomerResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated CustomerResponse Data = 2;
 * @return {!Array<!proto.Protos.CustomerResponse>}
 */
proto.Protos.GetAllCustomerResponse.prototype.getDataList = function() {
  return /** @type{!Array<!proto.Protos.CustomerResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Protos.CustomerResponse, 2));
};


/**
 * @param {!Array<!proto.Protos.CustomerResponse>} value
 * @return {!proto.Protos.GetAllCustomerResponse} returns this
*/
proto.Protos.GetAllCustomerResponse.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Protos.CustomerResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Protos.CustomerResponse}
 */
proto.Protos.GetAllCustomerResponse.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Protos.CustomerResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Protos.GetAllCustomerResponse} returns this
 */
proto.Protos.GetAllCustomerResponse.prototype.clearDataList = function() {
  return this.setDataList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CustomerResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CustomerResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CustomerResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CustomerResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nombre: jspb.Message.getFieldWithDefault(msg, 2, ""),
    apellidopaterno: jspb.Message.getFieldWithDefault(msg, 3, ""),
    apellidomaterno: jspb.Message.getFieldWithDefault(msg, 4, ""),
    celular: jspb.Message.getFieldWithDefault(msg, 5, ""),
    email: jspb.Message.getFieldWithDefault(msg, 6, ""),
    tipodocumento: jspb.Message.getFieldWithDefault(msg, 7, 0),
    nrodocumento: jspb.Message.getFieldWithDefault(msg, 8, 0),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CustomerResponse}
 */
proto.Protos.CustomerResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CustomerResponse;
  return proto.Protos.CustomerResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CustomerResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CustomerResponse}
 */
proto.Protos.CustomerResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNombre(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApellidopaterno(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setApellidomaterno(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCelular(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 7:
      var value = /** @type {!proto.Protos.CustomerDocumentType} */ (reader.readEnum());
      msg.setTipodocumento(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNrodocumento(value);
      break;
    case 9:
      var value = /** @type {!proto.Protos.CustomerState} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CustomerResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CustomerResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CustomerResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CustomerResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNombre();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getApellidopaterno();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getApellidomaterno();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCelular();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getTipodocumento();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getNrodocumento();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.CustomerResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Nombre = 2;
 * @return {string}
 */
proto.Protos.CustomerResponse.prototype.getNombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setNombre = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string ApellidoPaterno = 3;
 * @return {string}
 */
proto.Protos.CustomerResponse.prototype.getApellidopaterno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setApellidopaterno = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string ApellidoMaterno = 4;
 * @return {string}
 */
proto.Protos.CustomerResponse.prototype.getApellidomaterno = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setApellidomaterno = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Celular = 5;
 * @return {string}
 */
proto.Protos.CustomerResponse.prototype.getCelular = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setCelular = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string email = 6;
 * @return {string}
 */
proto.Protos.CustomerResponse.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional CustomerDocumentType TipoDocumento = 7;
 * @return {!proto.Protos.CustomerDocumentType}
 */
proto.Protos.CustomerResponse.prototype.getTipodocumento = function() {
  return /** @type {!proto.Protos.CustomerDocumentType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.Protos.CustomerDocumentType} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setTipodocumento = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional int32 NroDocumento = 8;
 * @return {number}
 */
proto.Protos.CustomerResponse.prototype.getNrodocumento = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setNrodocumento = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional CustomerState State = 9;
 * @return {!proto.Protos.CustomerState}
 */
proto.Protos.CustomerResponse.prototype.getState = function() {
  return /** @type {!proto.Protos.CustomerState} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.Protos.CustomerState} value
 * @return {!proto.Protos.CustomerResponse} returns this
 */
proto.Protos.CustomerResponse.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * @enum {number}
 */
proto.Protos.CustomerDocumentType = {
  DNI: 0,
  CE: 1
};

/**
 * @enum {number}
 */
proto.Protos.CustomerState = {
  CUSTOMER_INACTIVO: 0,
  CUSTOMER_ACTIVO: 1,
  CUSTOMER_COMPLETADO: 2
};

goog.object.extend(exports, proto.Protos);
