// source: Protos/Office.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var Protos_Common_pb = require('../Protos/Common_pb.js');
goog.object.extend(proto, Protos_Common_pb);
goog.exportSymbol('proto.CancelOfficeRequest', null, global);
goog.exportSymbol('proto.CancelOfficeResponse', null, global);
goog.exportSymbol('proto.CreateOfficeRequest', null, global);
goog.exportSymbol('proto.CreateOfficeResponse', null, global);
goog.exportSymbol('proto.GetAllOfficeRequest', null, global);
goog.exportSymbol('proto.GetAllOfficeResponse', null, global);
goog.exportSymbol('proto.GetOfficeRequest', null, global);
goog.exportSymbol('proto.GetOfficeResponse', null, global);
goog.exportSymbol('proto.OfficeResponse', null, global);
goog.exportSymbol('proto.OfficeStatus', null, global);
goog.exportSymbol('proto.UpdateOfficeRequest', null, global);
goog.exportSymbol('proto.UpdateOfficeResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CreateOfficeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CreateOfficeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CreateOfficeRequest.displayName = 'proto.CreateOfficeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CreateOfficeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CreateOfficeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CreateOfficeResponse.displayName = 'proto.CreateOfficeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UpdateOfficeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UpdateOfficeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UpdateOfficeRequest.displayName = 'proto.UpdateOfficeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UpdateOfficeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UpdateOfficeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UpdateOfficeResponse.displayName = 'proto.UpdateOfficeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CancelOfficeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CancelOfficeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CancelOfficeRequest.displayName = 'proto.CancelOfficeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CancelOfficeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CancelOfficeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.CancelOfficeResponse.displayName = 'proto.CancelOfficeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetOfficeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetOfficeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetOfficeRequest.displayName = 'proto.GetOfficeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetOfficeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetOfficeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetOfficeResponse.displayName = 'proto.GetOfficeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetAllOfficeRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.GetAllOfficeRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetAllOfficeRequest.displayName = 'proto.GetAllOfficeRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GetAllOfficeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GetAllOfficeResponse.repeatedFields_, null);
};
goog.inherits(proto.GetAllOfficeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GetAllOfficeResponse.displayName = 'proto.GetAllOfficeResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.OfficeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.OfficeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.OfficeResponse.displayName = 'proto.OfficeResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CreateOfficeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.CreateOfficeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CreateOfficeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateOfficeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    nombre: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ubicacion: jspb.Message.getFieldWithDefault(msg, 2, ""),
    montodiario: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    numeroclientes: jspb.Message.getFieldWithDefault(msg, 4, 0),
    saldo: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    estado: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CreateOfficeRequest}
 */
proto.CreateOfficeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CreateOfficeRequest;
  return proto.CreateOfficeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CreateOfficeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CreateOfficeRequest}
 */
proto.CreateOfficeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNombre(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUbicacion(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMontodiario(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumeroclientes(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSaldo(value);
      break;
    case 6:
      var value = /** @type {!proto.OfficeStatus} */ (reader.readEnum());
      msg.setEstado(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CreateOfficeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CreateOfficeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CreateOfficeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateOfficeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNombre();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUbicacion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMontodiario();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getNumeroclientes();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSaldo();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getEstado();
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    );
  }
};


/**
 * optional string Nombre = 1;
 * @return {string}
 */
proto.CreateOfficeRequest.prototype.getNombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.CreateOfficeRequest} returns this
 */
proto.CreateOfficeRequest.prototype.setNombre = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string Ubicacion = 2;
 * @return {string}
 */
proto.CreateOfficeRequest.prototype.getUbicacion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.CreateOfficeRequest} returns this
 */
proto.CreateOfficeRequest.prototype.setUbicacion = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional double MontoDiario = 3;
 * @return {number}
 */
proto.CreateOfficeRequest.prototype.getMontodiario = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CreateOfficeRequest} returns this
 */
proto.CreateOfficeRequest.prototype.setMontodiario = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional int32 NumeroClientes = 4;
 * @return {number}
 */
proto.CreateOfficeRequest.prototype.getNumeroclientes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.CreateOfficeRequest} returns this
 */
proto.CreateOfficeRequest.prototype.setNumeroclientes = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional double Saldo = 5;
 * @return {number}
 */
proto.CreateOfficeRequest.prototype.getSaldo = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.CreateOfficeRequest} returns this
 */
proto.CreateOfficeRequest.prototype.setSaldo = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional OfficeStatus Estado = 6;
 * @return {!proto.OfficeStatus}
 */
proto.CreateOfficeRequest.prototype.getEstado = function() {
  return /** @type {!proto.OfficeStatus} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {!proto.OfficeStatus} value
 * @return {!proto.CreateOfficeRequest} returns this
 */
proto.CreateOfficeRequest.prototype.setEstado = function(value) {
  return jspb.Message.setProto3EnumField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CreateOfficeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.CreateOfficeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CreateOfficeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateOfficeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.OfficeResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CreateOfficeResponse}
 */
proto.CreateOfficeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CreateOfficeResponse;
  return proto.CreateOfficeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CreateOfficeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CreateOfficeResponse}
 */
proto.CreateOfficeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.OfficeResponse;
      reader.readMessage(value,proto.OfficeResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CreateOfficeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CreateOfficeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CreateOfficeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateOfficeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.OfficeResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.CreateOfficeResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.CreateOfficeResponse} returns this
*/
proto.CreateOfficeResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CreateOfficeResponse} returns this
 */
proto.CreateOfficeResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CreateOfficeResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional OfficeResponse Data = 2;
 * @return {?proto.OfficeResponse}
 */
proto.CreateOfficeResponse.prototype.getData = function() {
  return /** @type{?proto.OfficeResponse} */ (
    jspb.Message.getWrapperField(this, proto.OfficeResponse, 2));
};


/**
 * @param {?proto.OfficeResponse|undefined} value
 * @return {!proto.CreateOfficeResponse} returns this
*/
proto.CreateOfficeResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CreateOfficeResponse} returns this
 */
proto.CreateOfficeResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CreateOfficeResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UpdateOfficeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.UpdateOfficeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UpdateOfficeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateOfficeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nombre: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ubicacion: jspb.Message.getFieldWithDefault(msg, 3, ""),
    montodiario: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    numeroclientes: jspb.Message.getFieldWithDefault(msg, 5, 0),
    saldo: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    estado: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UpdateOfficeRequest}
 */
proto.UpdateOfficeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UpdateOfficeRequest;
  return proto.UpdateOfficeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UpdateOfficeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UpdateOfficeRequest}
 */
proto.UpdateOfficeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNombre(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUbicacion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMontodiario(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumeroclientes(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSaldo(value);
      break;
    case 7:
      var value = /** @type {!proto.OfficeStatus} */ (reader.readEnum());
      msg.setEstado(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UpdateOfficeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UpdateOfficeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UpdateOfficeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateOfficeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNombre();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUbicacion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMontodiario();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getNumeroclientes();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getSaldo();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getEstado();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.UpdateOfficeRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Nombre = 2;
 * @return {string}
 */
proto.UpdateOfficeRequest.prototype.getNombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setNombre = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Ubicacion = 3;
 * @return {string}
 */
proto.UpdateOfficeRequest.prototype.getUbicacion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setUbicacion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double MontoDiario = 4;
 * @return {number}
 */
proto.UpdateOfficeRequest.prototype.getMontodiario = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setMontodiario = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int32 NumeroClientes = 5;
 * @return {number}
 */
proto.UpdateOfficeRequest.prototype.getNumeroclientes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setNumeroclientes = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double Saldo = 6;
 * @return {number}
 */
proto.UpdateOfficeRequest.prototype.getSaldo = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setSaldo = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional OfficeStatus Estado = 7;
 * @return {!proto.OfficeStatus}
 */
proto.UpdateOfficeRequest.prototype.getEstado = function() {
  return /** @type {!proto.OfficeStatus} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.OfficeStatus} value
 * @return {!proto.UpdateOfficeRequest} returns this
 */
proto.UpdateOfficeRequest.prototype.setEstado = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UpdateOfficeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.UpdateOfficeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UpdateOfficeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateOfficeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.OfficeResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UpdateOfficeResponse}
 */
proto.UpdateOfficeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UpdateOfficeResponse;
  return proto.UpdateOfficeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UpdateOfficeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UpdateOfficeResponse}
 */
proto.UpdateOfficeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.OfficeResponse;
      reader.readMessage(value,proto.OfficeResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UpdateOfficeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UpdateOfficeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UpdateOfficeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UpdateOfficeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.OfficeResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.UpdateOfficeResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.UpdateOfficeResponse} returns this
*/
proto.UpdateOfficeResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UpdateOfficeResponse} returns this
 */
proto.UpdateOfficeResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UpdateOfficeResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional OfficeResponse Data = 2;
 * @return {?proto.OfficeResponse}
 */
proto.UpdateOfficeResponse.prototype.getData = function() {
  return /** @type{?proto.OfficeResponse} */ (
    jspb.Message.getWrapperField(this, proto.OfficeResponse, 2));
};


/**
 * @param {?proto.OfficeResponse|undefined} value
 * @return {!proto.UpdateOfficeResponse} returns this
*/
proto.UpdateOfficeResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UpdateOfficeResponse} returns this
 */
proto.UpdateOfficeResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UpdateOfficeResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CancelOfficeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.CancelOfficeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CancelOfficeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CancelOfficeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CancelOfficeRequest}
 */
proto.CancelOfficeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CancelOfficeRequest;
  return proto.CancelOfficeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CancelOfficeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CancelOfficeRequest}
 */
proto.CancelOfficeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CancelOfficeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CancelOfficeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CancelOfficeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CancelOfficeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.CancelOfficeRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.CancelOfficeRequest} returns this
 */
proto.CancelOfficeRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CancelOfficeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.CancelOfficeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CancelOfficeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CancelOfficeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CancelOfficeResponse}
 */
proto.CancelOfficeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CancelOfficeResponse;
  return proto.CancelOfficeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CancelOfficeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CancelOfficeResponse}
 */
proto.CancelOfficeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CancelOfficeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CancelOfficeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CancelOfficeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CancelOfficeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.CancelOfficeResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.CancelOfficeResponse} returns this
*/
proto.CancelOfficeResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.CancelOfficeResponse} returns this
 */
proto.CancelOfficeResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.CancelOfficeResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetOfficeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.GetOfficeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetOfficeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetOfficeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetOfficeRequest}
 */
proto.GetOfficeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetOfficeRequest;
  return proto.GetOfficeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetOfficeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetOfficeRequest}
 */
proto.GetOfficeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetOfficeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetOfficeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetOfficeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetOfficeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.GetOfficeRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.GetOfficeRequest} returns this
 */
proto.GetOfficeRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetOfficeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.GetOfficeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetOfficeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetOfficeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.OfficeResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetOfficeResponse}
 */
proto.GetOfficeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetOfficeResponse;
  return proto.GetOfficeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetOfficeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetOfficeResponse}
 */
proto.GetOfficeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.OfficeResponse;
      reader.readMessage(value,proto.OfficeResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetOfficeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetOfficeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetOfficeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetOfficeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.OfficeResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.GetOfficeResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.GetOfficeResponse} returns this
*/
proto.GetOfficeResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetOfficeResponse} returns this
 */
proto.GetOfficeResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetOfficeResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional OfficeResponse Data = 2;
 * @return {?proto.OfficeResponse}
 */
proto.GetOfficeResponse.prototype.getData = function() {
  return /** @type{?proto.OfficeResponse} */ (
    jspb.Message.getWrapperField(this, proto.OfficeResponse, 2));
};


/**
 * @param {?proto.OfficeResponse|undefined} value
 * @return {!proto.GetOfficeResponse} returns this
*/
proto.GetOfficeResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetOfficeResponse} returns this
 */
proto.GetOfficeResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetOfficeResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetAllOfficeRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.GetAllOfficeRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetAllOfficeRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetAllOfficeRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetAllOfficeRequest}
 */
proto.GetAllOfficeRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetAllOfficeRequest;
  return proto.GetAllOfficeRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetAllOfficeRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetAllOfficeRequest}
 */
proto.GetAllOfficeRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetAllOfficeRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetAllOfficeRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetAllOfficeRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetAllOfficeRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GetAllOfficeResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GetAllOfficeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.GetAllOfficeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GetAllOfficeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetAllOfficeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.OfficeResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GetAllOfficeResponse}
 */
proto.GetAllOfficeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GetAllOfficeResponse;
  return proto.GetAllOfficeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GetAllOfficeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GetAllOfficeResponse}
 */
proto.GetAllOfficeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.OfficeResponse;
      reader.readMessage(value,proto.OfficeResponse.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GetAllOfficeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GetAllOfficeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GetAllOfficeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GetAllOfficeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.OfficeResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.GetAllOfficeResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.GetAllOfficeResponse} returns this
*/
proto.GetAllOfficeResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.GetAllOfficeResponse} returns this
 */
proto.GetAllOfficeResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.GetAllOfficeResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated OfficeResponse Data = 2;
 * @return {!Array<!proto.OfficeResponse>}
 */
proto.GetAllOfficeResponse.prototype.getDataList = function() {
  return /** @type{!Array<!proto.OfficeResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.OfficeResponse, 2));
};


/**
 * @param {!Array<!proto.OfficeResponse>} value
 * @return {!proto.GetAllOfficeResponse} returns this
*/
proto.GetAllOfficeResponse.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.OfficeResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.OfficeResponse}
 */
proto.GetAllOfficeResponse.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.OfficeResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.GetAllOfficeResponse} returns this
 */
proto.GetAllOfficeResponse.prototype.clearDataList = function() {
  return this.setDataList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.OfficeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.OfficeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.OfficeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OfficeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    nombre: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ubicacion: jspb.Message.getFieldWithDefault(msg, 3, ""),
    montodiario: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    numeroclientes: jspb.Message.getFieldWithDefault(msg, 5, 0),
    saldo: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    estado: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.OfficeResponse}
 */
proto.OfficeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.OfficeResponse;
  return proto.OfficeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.OfficeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.OfficeResponse}
 */
proto.OfficeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNombre(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUbicacion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMontodiario(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNumeroclientes(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSaldo(value);
      break;
    case 7:
      var value = /** @type {!proto.OfficeStatus} */ (reader.readEnum());
      msg.setEstado(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.OfficeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.OfficeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.OfficeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.OfficeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getNombre();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUbicacion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMontodiario();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getNumeroclientes();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getSaldo();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getEstado();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.OfficeResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string Nombre = 2;
 * @return {string}
 */
proto.OfficeResponse.prototype.getNombre = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setNombre = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string Ubicacion = 3;
 * @return {string}
 */
proto.OfficeResponse.prototype.getUbicacion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setUbicacion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional double MontoDiario = 4;
 * @return {number}
 */
proto.OfficeResponse.prototype.getMontodiario = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setMontodiario = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int32 NumeroClientes = 5;
 * @return {number}
 */
proto.OfficeResponse.prototype.getNumeroclientes = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setNumeroclientes = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional double Saldo = 6;
 * @return {number}
 */
proto.OfficeResponse.prototype.getSaldo = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setSaldo = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional OfficeStatus Estado = 7;
 * @return {!proto.OfficeStatus}
 */
proto.OfficeResponse.prototype.getEstado = function() {
  return /** @type {!proto.OfficeStatus} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.OfficeStatus} value
 * @return {!proto.OfficeResponse} returns this
 */
proto.OfficeResponse.prototype.setEstado = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.OfficeStatus = {
  INACTIVA: 0,
  ACTIVA: 1,
  COMPLETADA: 2
};

goog.object.extend(exports, proto);
