/**
 * @fileoverview gRPC-Web generated client stub for Protos
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.21.6
// source: Protos/Transaction.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import '../Protos/Transaction_pb'; // Solo importamos el archivo para que se ejecute en el navegador

// Extraemos las clases directamente del objeto global secreto de Google Protobuf
const Protos_Transaction_pb = (window as any).proto.Protos || (window as any).proto;


export class TransactionsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateTransaction = new grpcWeb.MethodDescriptor(
    '/Protos.Transactions/CreateTransaction',
    grpcWeb.MethodType.UNARY,
    Protos_Transaction_pb.CreateTransactionRequest,
    Protos_Transaction_pb.CreateTransactionResponse,
    (request: Protos_Transaction_pb.CreateTransactionRequest) => {
      return request.serializeBinary();
    },
    Protos_Transaction_pb.CreateTransactionResponse.deserializeBinary
  );

  createTransaction(
    request: Protos_Transaction_pb.CreateTransactionRequest,
    metadata: grpcWeb.Metadata | null): Promise<Protos_Transaction_pb.CreateTransactionResponse>;

  createTransaction(
    request: Protos_Transaction_pb.CreateTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.CreateTransactionResponse) => void): grpcWeb.ClientReadableStream<Protos_Transaction_pb.CreateTransactionResponse>;

  createTransaction(
    request: Protos_Transaction_pb.CreateTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.CreateTransactionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Protos.Transactions/CreateTransaction',
        request,
        metadata || {},
        this.methodDescriptorCreateTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Protos.Transactions/CreateTransaction',
    request,
    metadata || {},
    this.methodDescriptorCreateTransaction);
  }

  methodDescriptorUpdateTransaction = new grpcWeb.MethodDescriptor(
    '/Protos.Transactions/UpdateTransaction',
    grpcWeb.MethodType.UNARY,
    Protos_Transaction_pb.UpdateTransactionRequest,
    Protos_Transaction_pb.UpdateTransactionResponse,
    (request: Protos_Transaction_pb.UpdateTransactionRequest) => {
      return request.serializeBinary();
    },
    Protos_Transaction_pb.UpdateTransactionResponse.deserializeBinary
  );

  updateTransaction(
    request: Protos_Transaction_pb.UpdateTransactionRequest,
    metadata: grpcWeb.Metadata | null): Promise<Protos_Transaction_pb.UpdateTransactionResponse>;

  updateTransaction(
    request: Protos_Transaction_pb.UpdateTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.UpdateTransactionResponse) => void): grpcWeb.ClientReadableStream<Protos_Transaction_pb.UpdateTransactionResponse>;

  updateTransaction(
    request: Protos_Transaction_pb.UpdateTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.UpdateTransactionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Protos.Transactions/UpdateTransaction',
        request,
        metadata || {},
        this.methodDescriptorUpdateTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Protos.Transactions/UpdateTransaction',
    request,
    metadata || {},
    this.methodDescriptorUpdateTransaction);
  }

  methodDescriptorCancelTransaction = new grpcWeb.MethodDescriptor(
    '/Protos.Transactions/CancelTransaction',
    grpcWeb.MethodType.UNARY,
    Protos_Transaction_pb.CancelTransactionRequest,
    Protos_Transaction_pb.CancelTransactionResponse,
    (request: Protos_Transaction_pb.CancelTransactionRequest) => {
      return request.serializeBinary();
    },
    Protos_Transaction_pb.CancelTransactionResponse.deserializeBinary
  );

  cancelTransaction(
    request: Protos_Transaction_pb.CancelTransactionRequest,
    metadata: grpcWeb.Metadata | null): Promise<Protos_Transaction_pb.CancelTransactionResponse>;

  cancelTransaction(
    request: Protos_Transaction_pb.CancelTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.CancelTransactionResponse) => void): grpcWeb.ClientReadableStream<Protos_Transaction_pb.CancelTransactionResponse>;

  cancelTransaction(
    request: Protos_Transaction_pb.CancelTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.CancelTransactionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Protos.Transactions/CancelTransaction',
        request,
        metadata || {},
        this.methodDescriptorCancelTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Protos.Transactions/CancelTransaction',
    request,
    metadata || {},
    this.methodDescriptorCancelTransaction);
  }

  methodDescriptorGetTransaction = new grpcWeb.MethodDescriptor(
    '/Protos.Transactions/GetTransaction',
    grpcWeb.MethodType.UNARY,
    Protos_Transaction_pb.GetTransactionRequest,
    Protos_Transaction_pb.GetTransactionResponse,
    (request: Protos_Transaction_pb.GetTransactionRequest) => {
      return request.serializeBinary();
    },
    Protos_Transaction_pb.GetTransactionResponse.deserializeBinary
  );

  getTransaction(
    request: Protos_Transaction_pb.GetTransactionRequest,
    metadata: grpcWeb.Metadata | null): Promise<Protos_Transaction_pb.GetTransactionResponse>;

  getTransaction(
    request: Protos_Transaction_pb.GetTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.GetTransactionResponse) => void): grpcWeb.ClientReadableStream<Protos_Transaction_pb.GetTransactionResponse>;

  getTransaction(
    request: Protos_Transaction_pb.GetTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.GetTransactionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Protos.Transactions/GetTransaction',
        request,
        metadata || {},
        this.methodDescriptorGetTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Protos.Transactions/GetTransaction',
    request,
    metadata || {},
    this.methodDescriptorGetTransaction);
  }

  methodDescriptorGetAllTransaction = new grpcWeb.MethodDescriptor(
    '/Protos.Transactions/GetAllTransaction',
    grpcWeb.MethodType.UNARY,
    Protos_Transaction_pb.GetAllTransactionRequest,
    Protos_Transaction_pb.GetAllTransactionResponse,
    (request: Protos_Transaction_pb.GetAllTransactionRequest) => {
      return request.serializeBinary();
    },
    Protos_Transaction_pb.GetAllTransactionResponse.deserializeBinary
  );

  getAllTransaction(
    request: Protos_Transaction_pb.GetAllTransactionRequest,
    metadata: grpcWeb.Metadata | null): Promise<Protos_Transaction_pb.GetAllTransactionResponse>;

  getAllTransaction(
    request: Protos_Transaction_pb.GetAllTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.GetAllTransactionResponse) => void): grpcWeb.ClientReadableStream<Protos_Transaction_pb.GetAllTransactionResponse>;

  getAllTransaction(
    request: Protos_Transaction_pb.GetAllTransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Protos_Transaction_pb.GetAllTransactionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/Protos.Transactions/GetAllTransaction',
        request,
        metadata || {},
        this.methodDescriptorGetAllTransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/Protos.Transactions/GetAllTransaction',
    request,
    metadata || {},
    this.methodDescriptorGetAllTransaction);
  }

}

