// source: Protos/Transaction.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var Protos_Common_pb = require('../Protos/Common_pb.js');
goog.object.extend(proto, Protos_Common_pb);
goog.exportSymbol('proto.Protos.CancelTransactionRequest', null, global);
goog.exportSymbol('proto.Protos.CancelTransactionResponse', null, global);
goog.exportSymbol('proto.Protos.CreateTransactionRequest', null, global);
goog.exportSymbol('proto.Protos.CreateTransactionResponse', null, global);
goog.exportSymbol('proto.Protos.GetAllTransactionRequest', null, global);
goog.exportSymbol('proto.Protos.GetAllTransactionResponse', null, global);
goog.exportSymbol('proto.Protos.GetTransactionRequest', null, global);
goog.exportSymbol('proto.Protos.GetTransactionResponse', null, global);
goog.exportSymbol('proto.Protos.TransactionResponse', null, global);
goog.exportSymbol('proto.Protos.TransactionState', null, global);
goog.exportSymbol('proto.Protos.TransactionType', null, global);
goog.exportSymbol('proto.Protos.UpdateTransactionRequest', null, global);
goog.exportSymbol('proto.Protos.UpdateTransactionResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CreateTransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CreateTransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CreateTransactionRequest.displayName = 'proto.Protos.CreateTransactionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CreateTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CreateTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CreateTransactionResponse.displayName = 'proto.Protos.CreateTransactionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.UpdateTransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.UpdateTransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.UpdateTransactionRequest.displayName = 'proto.Protos.UpdateTransactionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.UpdateTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.UpdateTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.UpdateTransactionResponse.displayName = 'proto.Protos.UpdateTransactionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CancelTransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CancelTransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CancelTransactionRequest.displayName = 'proto.Protos.CancelTransactionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.CancelTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.CancelTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.CancelTransactionResponse.displayName = 'proto.Protos.CancelTransactionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetTransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetTransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetTransactionRequest.displayName = 'proto.Protos.GetTransactionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetTransactionResponse.displayName = 'proto.Protos.GetTransactionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetAllTransactionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.GetAllTransactionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetAllTransactionRequest.displayName = 'proto.Protos.GetAllTransactionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.GetAllTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Protos.GetAllTransactionResponse.repeatedFields_, null);
};
goog.inherits(proto.Protos.GetAllTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.GetAllTransactionResponse.displayName = 'proto.Protos.GetAllTransactionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Protos.TransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Protos.TransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Protos.TransactionResponse.displayName = 'proto.Protos.TransactionResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CreateTransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CreateTransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CreateTransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateTransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    tipomovimiento: jspb.Message.getFieldWithDefault(msg, 2, 0),
    monto: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    moneda: jspb.Message.getFieldWithDefault(msg, 4, ""),
    descripcion: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sede: jspb.Message.getFieldWithDefault(msg, 6, ""),
    fecharealizacion: (f = msg.getFecharealizacion()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CreateTransactionRequest}
 */
proto.Protos.CreateTransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CreateTransactionRequest;
  return proto.Protos.CreateTransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CreateTransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CreateTransactionRequest}
 */
proto.Protos.CreateTransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAccountid(value);
      break;
    case 2:
      var value = /** @type {!proto.Protos.TransactionType} */ (reader.readEnum());
      msg.setTipomovimiento(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMonto(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoneda(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescripcion(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSede(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFecharealizacion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CreateTransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CreateTransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CreateTransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateTransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getTipomovimiento();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMonto();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getMoneda();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescripcion();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSede();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getFecharealizacion();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 AccountId = 1;
 * @return {number}
 */
proto.Protos.CreateTransactionRequest.prototype.getAccountid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional TransactionType TipoMovimiento = 2;
 * @return {!proto.Protos.TransactionType}
 */
proto.Protos.CreateTransactionRequest.prototype.getTipomovimiento = function() {
  return /** @type {!proto.Protos.TransactionType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.Protos.TransactionType} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.setTipomovimiento = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional double Monto = 3;
 * @return {number}
 */
proto.Protos.CreateTransactionRequest.prototype.getMonto = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.setMonto = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional string Moneda = 4;
 * @return {string}
 */
proto.Protos.CreateTransactionRequest.prototype.getMoneda = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.setMoneda = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string Descripcion = 5;
 * @return {string}
 */
proto.Protos.CreateTransactionRequest.prototype.getDescripcion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.setDescripcion = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string Sede = 6;
 * @return {string}
 */
proto.Protos.CreateTransactionRequest.prototype.getSede = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.setSede = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional google.protobuf.Timestamp FechaRealizacion = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Protos.CreateTransactionRequest.prototype.getFecharealizacion = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Protos.CreateTransactionRequest} returns this
*/
proto.Protos.CreateTransactionRequest.prototype.setFecharealizacion = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.CreateTransactionRequest} returns this
 */
proto.Protos.CreateTransactionRequest.prototype.clearFecharealizacion = function() {
  return this.setFecharealizacion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.CreateTransactionRequest.prototype.hasFecharealizacion = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CreateTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CreateTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CreateTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CreateTransactionResponse}
 */
proto.Protos.CreateTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CreateTransactionResponse;
  return proto.Protos.CreateTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CreateTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CreateTransactionResponse}
 */
proto.Protos.CreateTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CreateTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CreateTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CreateTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CreateTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.CreateTransactionResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.CreateTransactionResponse} returns this
*/
proto.Protos.CreateTransactionResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.CreateTransactionResponse} returns this
 */
proto.Protos.CreateTransactionResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.CreateTransactionResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.UpdateTransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.UpdateTransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.UpdateTransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateTransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accountid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    tipomovimiento: jspb.Message.getFieldWithDefault(msg, 3, 0),
    monto: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    moneda: jspb.Message.getFieldWithDefault(msg, 5, ""),
    descripcion: jspb.Message.getFieldWithDefault(msg, 6, ""),
    sede: jspb.Message.getFieldWithDefault(msg, 7, ""),
    fecharealizacion: (f = msg.getFecharealizacion()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.UpdateTransactionRequest}
 */
proto.Protos.UpdateTransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.UpdateTransactionRequest;
  return proto.Protos.UpdateTransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.UpdateTransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.UpdateTransactionRequest}
 */
proto.Protos.UpdateTransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAccountid(value);
      break;
    case 3:
      var value = /** @type {!proto.Protos.TransactionType} */ (reader.readEnum());
      msg.setTipomovimiento(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMonto(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoneda(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescripcion(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSede(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFecharealizacion(value);
      break;
    case 9:
      var value = /** @type {!proto.Protos.TransactionState} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.UpdateTransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.UpdateTransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.UpdateTransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateTransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAccountid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTipomovimiento();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getMonto();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getMoneda();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescripcion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSede();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getFecharealizacion();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.UpdateTransactionRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 AccountId = 2;
 * @return {number}
 */
proto.Protos.UpdateTransactionRequest.prototype.getAccountid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional TransactionType TipoMovimiento = 3;
 * @return {!proto.Protos.TransactionType}
 */
proto.Protos.UpdateTransactionRequest.prototype.getTipomovimiento = function() {
  return /** @type {!proto.Protos.TransactionType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Protos.TransactionType} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setTipomovimiento = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional double Monto = 4;
 * @return {number}
 */
proto.Protos.UpdateTransactionRequest.prototype.getMonto = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setMonto = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string Moneda = 5;
 * @return {string}
 */
proto.Protos.UpdateTransactionRequest.prototype.getMoneda = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setMoneda = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string Descripcion = 6;
 * @return {string}
 */
proto.Protos.UpdateTransactionRequest.prototype.getDescripcion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setDescripcion = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string Sede = 7;
 * @return {string}
 */
proto.Protos.UpdateTransactionRequest.prototype.getSede = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setSede = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional google.protobuf.Timestamp FechaRealizacion = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Protos.UpdateTransactionRequest.prototype.getFecharealizacion = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
*/
proto.Protos.UpdateTransactionRequest.prototype.setFecharealizacion = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.clearFecharealizacion = function() {
  return this.setFecharealizacion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.UpdateTransactionRequest.prototype.hasFecharealizacion = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional TransactionState State = 9;
 * @return {!proto.Protos.TransactionState}
 */
proto.Protos.UpdateTransactionRequest.prototype.getState = function() {
  return /** @type {!proto.Protos.TransactionState} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.Protos.TransactionState} value
 * @return {!proto.Protos.UpdateTransactionRequest} returns this
 */
proto.Protos.UpdateTransactionRequest.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.UpdateTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.UpdateTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.UpdateTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.Protos.TransactionResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.UpdateTransactionResponse}
 */
proto.Protos.UpdateTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.UpdateTransactionResponse;
  return proto.Protos.UpdateTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.UpdateTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.UpdateTransactionResponse}
 */
proto.Protos.UpdateTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.Protos.TransactionResponse;
      reader.readMessage(value,proto.Protos.TransactionResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.UpdateTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.UpdateTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.UpdateTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.UpdateTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Protos.TransactionResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.UpdateTransactionResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.UpdateTransactionResponse} returns this
*/
proto.Protos.UpdateTransactionResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.UpdateTransactionResponse} returns this
 */
proto.Protos.UpdateTransactionResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.UpdateTransactionResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionResponse Data = 2;
 * @return {?proto.Protos.TransactionResponse}
 */
proto.Protos.UpdateTransactionResponse.prototype.getData = function() {
  return /** @type{?proto.Protos.TransactionResponse} */ (
    jspb.Message.getWrapperField(this, proto.Protos.TransactionResponse, 2));
};


/**
 * @param {?proto.Protos.TransactionResponse|undefined} value
 * @return {!proto.Protos.UpdateTransactionResponse} returns this
*/
proto.Protos.UpdateTransactionResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.UpdateTransactionResponse} returns this
 */
proto.Protos.UpdateTransactionResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.UpdateTransactionResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CancelTransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CancelTransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CancelTransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelTransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CancelTransactionRequest}
 */
proto.Protos.CancelTransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CancelTransactionRequest;
  return proto.Protos.CancelTransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CancelTransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CancelTransactionRequest}
 */
proto.Protos.CancelTransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CancelTransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CancelTransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CancelTransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelTransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.CancelTransactionRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.CancelTransactionRequest} returns this
 */
proto.Protos.CancelTransactionRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.CancelTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.CancelTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.CancelTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.CancelTransactionResponse}
 */
proto.Protos.CancelTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.CancelTransactionResponse;
  return proto.Protos.CancelTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.CancelTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.CancelTransactionResponse}
 */
proto.Protos.CancelTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.CancelTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.CancelTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.CancelTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.CancelTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.CancelTransactionResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.CancelTransactionResponse} returns this
*/
proto.Protos.CancelTransactionResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.CancelTransactionResponse} returns this
 */
proto.Protos.CancelTransactionResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.CancelTransactionResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetTransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetTransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetTransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetTransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetTransactionRequest}
 */
proto.Protos.GetTransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetTransactionRequest;
  return proto.Protos.GetTransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetTransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetTransactionRequest}
 */
proto.Protos.GetTransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetTransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetTransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetTransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetTransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.GetTransactionRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.GetTransactionRequest} returns this
 */
proto.Protos.GetTransactionRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.Protos.TransactionResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetTransactionResponse}
 */
proto.Protos.GetTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetTransactionResponse;
  return proto.Protos.GetTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetTransactionResponse}
 */
proto.Protos.GetTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.Protos.TransactionResponse;
      reader.readMessage(value,proto.Protos.TransactionResponse.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.Protos.TransactionResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.GetTransactionResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.GetTransactionResponse} returns this
*/
proto.Protos.GetTransactionResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.GetTransactionResponse} returns this
 */
proto.Protos.GetTransactionResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.GetTransactionResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TransactionResponse Data = 2;
 * @return {?proto.Protos.TransactionResponse}
 */
proto.Protos.GetTransactionResponse.prototype.getData = function() {
  return /** @type{?proto.Protos.TransactionResponse} */ (
    jspb.Message.getWrapperField(this, proto.Protos.TransactionResponse, 2));
};


/**
 * @param {?proto.Protos.TransactionResponse|undefined} value
 * @return {!proto.Protos.GetTransactionResponse} returns this
*/
proto.Protos.GetTransactionResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.GetTransactionResponse} returns this
 */
proto.Protos.GetTransactionResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.GetTransactionResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetAllTransactionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetAllTransactionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetAllTransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllTransactionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetAllTransactionRequest}
 */
proto.Protos.GetAllTransactionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetAllTransactionRequest;
  return proto.Protos.GetAllTransactionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetAllTransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetAllTransactionRequest}
 */
proto.Protos.GetAllTransactionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetAllTransactionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetAllTransactionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetAllTransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllTransactionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Protos.GetAllTransactionResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.GetAllTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.GetAllTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.GetAllTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    serverresponse: (f = msg.getServerresponse()) && Protos_Common_pb.ServerResponse.toObject(includeInstance, f),
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.Protos.TransactionResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.GetAllTransactionResponse}
 */
proto.Protos.GetAllTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.GetAllTransactionResponse;
  return proto.Protos.GetAllTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.GetAllTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.GetAllTransactionResponse}
 */
proto.Protos.GetAllTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new Protos_Common_pb.ServerResponse;
      reader.readMessage(value,Protos_Common_pb.ServerResponse.deserializeBinaryFromReader);
      msg.setServerresponse(value);
      break;
    case 2:
      var value = new proto.Protos.TransactionResponse;
      reader.readMessage(value,proto.Protos.TransactionResponse.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.GetAllTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.GetAllTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.GetAllTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.GetAllTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServerresponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      Protos_Common_pb.ServerResponse.serializeBinaryToWriter
    );
  }
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.Protos.TransactionResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ServerResponse ServerResponse = 1;
 * @return {?proto.ServerResponse}
 */
proto.Protos.GetAllTransactionResponse.prototype.getServerresponse = function() {
  return /** @type{?proto.ServerResponse} */ (
    jspb.Message.getWrapperField(this, Protos_Common_pb.ServerResponse, 1));
};


/**
 * @param {?proto.ServerResponse|undefined} value
 * @return {!proto.Protos.GetAllTransactionResponse} returns this
*/
proto.Protos.GetAllTransactionResponse.prototype.setServerresponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.GetAllTransactionResponse} returns this
 */
proto.Protos.GetAllTransactionResponse.prototype.clearServerresponse = function() {
  return this.setServerresponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.GetAllTransactionResponse.prototype.hasServerresponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated TransactionResponse Data = 2;
 * @return {!Array<!proto.Protos.TransactionResponse>}
 */
proto.Protos.GetAllTransactionResponse.prototype.getDataList = function() {
  return /** @type{!Array<!proto.Protos.TransactionResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Protos.TransactionResponse, 2));
};


/**
 * @param {!Array<!proto.Protos.TransactionResponse>} value
 * @return {!proto.Protos.GetAllTransactionResponse} returns this
*/
proto.Protos.GetAllTransactionResponse.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.Protos.TransactionResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Protos.TransactionResponse}
 */
proto.Protos.GetAllTransactionResponse.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.Protos.TransactionResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Protos.GetAllTransactionResponse} returns this
 */
proto.Protos.GetAllTransactionResponse.prototype.clearDataList = function() {
  return this.setDataList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Protos.TransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.Protos.TransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Protos.TransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.TransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accountid: jspb.Message.getFieldWithDefault(msg, 2, 0),
    tipomovimiento: jspb.Message.getFieldWithDefault(msg, 3, 0),
    monto: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    moneda: jspb.Message.getFieldWithDefault(msg, 5, ""),
    descripcion: jspb.Message.getFieldWithDefault(msg, 6, ""),
    sede: jspb.Message.getFieldWithDefault(msg, 7, ""),
    fecharealizacion: (f = msg.getFecharealizacion()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    state: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Protos.TransactionResponse}
 */
proto.Protos.TransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Protos.TransactionResponse;
  return proto.Protos.TransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Protos.TransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Protos.TransactionResponse}
 */
proto.Protos.TransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAccountid(value);
      break;
    case 3:
      var value = /** @type {!proto.Protos.TransactionType} */ (reader.readEnum());
      msg.setTipomovimiento(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMonto(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMoneda(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescripcion(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSede(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setFecharealizacion(value);
      break;
    case 9:
      var value = /** @type {!proto.Protos.TransactionState} */ (reader.readEnum());
      msg.setState(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Protos.TransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Protos.TransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Protos.TransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Protos.TransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getAccountid();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTipomovimiento();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getMonto();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getMoneda();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescripcion();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSede();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getFecharealizacion();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      9,
      f
    );
  }
};


/**
 * optional int32 Id = 1;
 * @return {number}
 */
proto.Protos.TransactionResponse.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 AccountId = 2;
 * @return {number}
 */
proto.Protos.TransactionResponse.prototype.getAccountid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setAccountid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional TransactionType TipoMovimiento = 3;
 * @return {!proto.Protos.TransactionType}
 */
proto.Protos.TransactionResponse.prototype.getTipomovimiento = function() {
  return /** @type {!proto.Protos.TransactionType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Protos.TransactionType} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setTipomovimiento = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional double Monto = 4;
 * @return {number}
 */
proto.Protos.TransactionResponse.prototype.getMonto = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setMonto = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional string Moneda = 5;
 * @return {string}
 */
proto.Protos.TransactionResponse.prototype.getMoneda = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setMoneda = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string Descripcion = 6;
 * @return {string}
 */
proto.Protos.TransactionResponse.prototype.getDescripcion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setDescripcion = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string Sede = 7;
 * @return {string}
 */
proto.Protos.TransactionResponse.prototype.getSede = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setSede = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional google.protobuf.Timestamp FechaRealizacion = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.Protos.TransactionResponse.prototype.getFecharealizacion = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.Protos.TransactionResponse} returns this
*/
proto.Protos.TransactionResponse.prototype.setFecharealizacion = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.clearFecharealizacion = function() {
  return this.setFecharealizacion(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Protos.TransactionResponse.prototype.hasFecharealizacion = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional TransactionState State = 9;
 * @return {!proto.Protos.TransactionState}
 */
proto.Protos.TransactionResponse.prototype.getState = function() {
  return /** @type {!proto.Protos.TransactionState} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {!proto.Protos.TransactionState} value
 * @return {!proto.Protos.TransactionResponse} returns this
 */
proto.Protos.TransactionResponse.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 9, value);
};


/**
 * @enum {number}
 */
proto.Protos.TransactionType = {
  TRANSFERENCIA: 0,
  GIRO: 1
};

/**
 * @enum {number}
 */
proto.Protos.TransactionState = {
  TRANSACTION_INACTIVO: 0,
  TRANSACTION_ACTIVO: 1,
  TRANSACTION_COMPLETADO: 2
};

goog.object.extend(exports, proto.Protos);
